ALTER TABLE users
    DROP CONSTRAINT IF EXISTS chk_users_status,
    ADD CONSTRAINT chk_users_status
        CHECK (status IN ('PENDING_VERIFICATION', 'ACTIVE', 'SUSPENDED', 'BANNED', 'FORCE_PASSWORD_RESET'));

UPDATE users SET status = 'BANNED' WHERE status = 'SUSPENDED' AND status NOT IN ('PENDING_VERIFICATION', 'ACTIVE', 'BANNED', 'FORCE_PASSWORD_RESET');
