DROP TRIGGER IF EXISTS trg_audit_user_preferences ON user_preferences;
DROP TRIGGER IF EXISTS trg_audit_user_verifications ON user_verifications;
DROP TRIGGER IF EXISTS trg_audit_user_identities ON user_identities;
DROP TRIGGER IF EXISTS trg_audit_dead_letter_jobs ON dead_letter_jobs;
DROP TRIGGER IF EXISTS trg_audit_jobs ON jobs;
DROP TRIGGER IF EXISTS trg_audit_notifications ON notifications;
DROP TRIGGER IF EXISTS trg_audit_user_notification_preferences ON user_notification_preferences;
DROP TRIGGER IF EXISTS trg_audit_global_templates ON global_templates;
DROP TRIGGER IF EXISTS trg_audit_permission_registry ON permission_registry;
DROP TRIGGER IF EXISTS trg_audit_webhook_deliveries ON webhook_deliveries;
DROP TRIGGER IF EXISTS trg_audit_webhooks ON webhooks;
DROP TRIGGER IF EXISTS trg_audit_api_keys ON api_keys;
DROP TRIGGER IF EXISTS trg_audit_file_metadata ON file_metadata;
DROP TRIGGER IF EXISTS trg_audit_feature_flags ON feature_flags;
DROP TRIGGER IF EXISTS trg_audit_settings ON settings;
DROP TRIGGER IF EXISTS trg_audit_role_permissions ON role_permissions;
DROP TRIGGER IF EXISTS trg_audit_permissions ON permissions;
DROP TRIGGER IF EXISTS trg_audit_roles ON roles;
DROP TRIGGER IF EXISTS trg_audit_sessions ON sessions;
DROP TRIGGER IF EXISTS trg_audit_users ON users;

DROP FUNCTION IF EXISTS prune_audit_logs;
DROP FUNCTION IF EXISTS prune_expired_sessions;
DROP FUNCTION IF EXISTS audit_trigger_func;

DELETE FROM global_templates;
DELETE FROM permission_registry;
DELETE FROM role_permissions;
DELETE FROM permissions;
DELETE FROM roles;
DELETE FROM user_consents;
DELETE FROM user_preferences;
DELETE FROM user_notification_preferences;
DELETE FROM notifications;
DELETE FROM user_verifications;
DELETE FROM user_identities;
DELETE FROM dead_letter_jobs;
DELETE FROM jobs;
DELETE FROM webhook_deliveries;
DELETE FROM webhooks;
DELETE FROM api_keys;
DELETE FROM file_metadata;
DELETE FROM feature_flags;
DELETE FROM settings;
DELETE FROM audit_logs;
DELETE FROM sessions;
DELETE FROM users;

DROP TABLE IF EXISTS user_consents;
DROP TABLE IF EXISTS user_preferences;
DROP TABLE IF EXISTS user_notification_preferences;
DROP TABLE IF EXISTS notifications;
DROP TABLE IF EXISTS user_verifications;
DROP TABLE IF EXISTS user_identities;
DROP TABLE IF EXISTS dead_letter_jobs;
DROP TABLE IF EXISTS jobs;
DROP TABLE IF EXISTS webhook_deliveries;
DROP TABLE IF EXISTS webhooks;
DROP TABLE IF EXISTS api_keys;
DROP TABLE IF EXISTS file_metadata;
DROP TABLE IF EXISTS feature_flags;
DROP TABLE IF EXISTS settings;
DROP TABLE IF EXISTS audit_logs;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS role_permissions;
DROP TABLE IF EXISTS permissions;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS permission_registry;
DROP TABLE IF EXISTS global_templates;

DROP EXTENSION IF EXISTS pgcrypto;
